[package]
name = "announcer_bot"
version = "0.3.0"
authors = ["sasjafor <john93412@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
codegen-units = 1

[dependencies]
log = "0.4.11"
env_logger = "0.8.2"
libsodium-sys = "0.2.6"
url = "2.2.0"
regex = "1.4.2"
lazy_static = "1.4.0"
rusqlite = "0.25.1"
rand = "0.8.0"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2.5" # needed so intrument works with async functions.
songbird = "0.1.6"

[dependencies.tokio]
version = "1.0.1"
features = ["macros", "signal", "rt-multi-thread"]

[dependencies.serenity]
default-features = false
features = [
    "builder",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "cache",
    "voice",
    "native_tls_backend",
]
version = "0.10.5"
